name: FaKenMovie
description: FaKenMovie using TMDB api.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  dio: ^3.0.9
  retrofit: ^1.3.4
  flutter_bloc: ^5.0.1
  provider: ^4.3.1
  riverpod: ^0.5.0
  freezed: ^0.11.2
  shared_preferences: ^0.5.8
  json_annotation: ^3.0.1
  get_it: ^4.0.2
  auto_route: ^0.6.1
  hive: ^1.4.1+1
  hive_flutter: ^0.3.0+2


dev_dependencies:
  flutter_test:
    sdk: flutter
  retrofit_generator: ^1.3.4
  build_runner: ^1.10.0
  json_serializable: ^3.3.0
  auto_route_generator: ^0.6.0
  #hive_generator: ^0.7.0+2

flutter:
  uses-material-design: true

scripts:
  derry.yaml

